// apps/solidjs-app/src/App.tsx
import { createSignal, For } from 'solid-js';
import {
  addTodo,
  todos,
  toggleTodo,
} from './infrastructure/services/Todo.service';

function App() {
  const [inputValue, setInputValue] = createSignal('');

  const onAddTodo = async () => {
    if (inputValue) {
      await addTodo(inputValue());

      setInputValue('');
    }
  };

  return (
    <div>
      <div>
        <For each={todos()}>
          {(todo) => {
            return (
              <div>
                <input
                  type="checkbox"
                  checked={todo.done}
                  onChange={() => toggleTodo(todo.id)}
                />

                {todo.text}
              </div>
            );
          }}
        </For>
      </div>
      <div>
        <input
          value={inputValue()}
          onChange={(event) => setInputValue(event.target.value)}
        />
      </div>
      <div>
        <button onClick={onAddTodo}>Add</button>
      </div>
    </div>
  );
}

export default App;

// apps/react-app/src/app/app.tsx
import { useCallback, useRef } from 'react';
import { useTodo } from '../infrastructure/services';

export function App() {
  const { todos, toggleTodo, addTodo } = useTodo();

  const textInputRef = useRef<HTMLInputElement>(null);

  const onAddTodo = useCallback(async () => {
    if (textInputRef.current) {
      await addTodo(textInputRef.current.value);

      textInputRef.current.value = '';
    }
  }, [addTodo]);

  return (
    <div>
      <div>
        {todos.map((todo) => {
          return (
            <div key={todo.id}>
              <input
                type="checkbox"
                checked={todo.done}
                onChange={() => toggleTodo(todo.id)}
              />

              {todo.text}
            </div>
          );
        })}
      </div>
      <div>
        <input ref={textInputRef} />
      </div>
      <div>
        <button onClick={onAddTodo}>Add</button>
      </div>
    </div>
  );
}

export default App;
